name: Ejecutar proyecto

on:
  workflow_dispatch:

jobs:
  ejecutar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Obtener datos IDENA
        run: curl -L "https://idena.navarra.es/ogc/wfs?service=WFS&request=GetCapabilities" -o idena-capabilities.xml
      - name: Obtener datos de Bera
                run: curl -L 'https://idena.navarra.es/ogc/wfs?service=WFS&version=2.0.0&request=GetFeature&typeNames=IDENA%3AOCUPAC_Pol_MCA_VE2000&outputFormat=application%2Fjson&count=20&CQL_FILTER=MUNICIPIO%3D%27Bera%27%20AND%20GRUPO%3D%27Frondosas%27' -o bera-frondosas.json
      - name: Guardar datos IDENA
        uses: actions/upload-artifact@v4
        with:
          name: idena-capabilities
          path: idena-capabilities.xml
      - name: Guardar datos de Bera
        uses: actions/upload-artifact@v4
        with:
          name: bera-frondosas
          path: bera-frondosas.json
      - name: Mostrar estructura
        run: |
          echo "Repositorio lurrak-lurrak-permacultura"
          echo "Flujo de trabajo ejecutado correctamente"
          find . -maxdepth 2 -type f | sort
